// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9oTX7CdwVOOgi0dE2fKX2CXN6hyYBRkc',
    appId: '1:511183205245:web:78577ab6f0a0248d44d214',
    messagingSenderId: '511183205245',
    projectId: 'squidly1408',
    authDomain: 'squidly1408.firebaseapp.com',
    storageBucket: 'squidly1408.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC5QrLEsm8l5eco0MebOLO294mD7zS7bg',
    appId: '1:511183205245:android:bd8e20326fc3493544d214',
    messagingSenderId: '511183205245',
    projectId: 'squidly1408',
    storageBucket: 'squidly1408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAILAojIGlU1PQZpO52ngr66LT18-PcK2Y',
    appId: '1:511183205245:ios:30007d57139a509b44d214',
    messagingSenderId: '511183205245',
    projectId: 'squidly1408',
    storageBucket: 'squidly1408.appspot.com',
    iosClientId: '511183205245-0cq74ultbn0mnavtm7nino9gi83kdqvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAILAojIGlU1PQZpO52ngr66LT18-PcK2Y',
    appId: '1:511183205245:ios:30007d57139a509b44d214',
    messagingSenderId: '511183205245',
    projectId: 'squidly1408',
    storageBucket: 'squidly1408.appspot.com',
    iosClientId: '511183205245-0cq74ultbn0mnavtm7nino9gi83kdqvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
